version: '3'

services:
########################
# Setup server container
########################
    server:
        build: ./server
        expose:
            - ${APP_SERVER_PORT}
        environment: 
            APP_SERVER_PORT: ${APP_SERVER_PORT}
        ports:
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
            - ./server/app/data
        command: npm run dev

########################
# Setup client container
########################
    client:
        build: ./client
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose:
            - ${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - ./client/app/data
        links:
            - server
        command: npm start